### ISSUE TITLE
Can we move the style into a separate page CSS file?

### ISSUE THREAD

**Issue by kakyoism** [mdings/electron-tooltip#5]
Newbie here.

In the sample code

```js
// example
// in the render process..
const tt = require('electron-tooltip')
tt({
  position: 'bottom',
  width: 200,
  style: {
    backgroundColor: '#f2f3f4',
    borderRadius: '4px'
  }
})
```

Seems that the tooltip is styled in place in the JS code. Would it be possible to move this into the common CSS file of the page of interest? Something like this

```js
tt({
  position: 'bottom',
  width: 200,
  style: 'thispage.css'
})
```

**Comment by mdings** [comment]
Well we'd probably have to read the file through nodes fs-module and then find the classes or ids that apply to the tooltip and attach them. That seems like extra complexity for something that's otherwise trivial. Do you have any good reasons to want this other then project file organisation?
