### ISSUE TITLE
how will i explain to my parents that a tooltip uses 20mb ram 😳 

### ISSUE THREAD

**Issue by ghost** [mdings/electron-tooltip#7]
hehehea... use JavaFX ;)

**Comment by mdings** [comment]
Just gently write it in a letter 😀

**Comment by ghost** [comment]
Well us kewl gemers use OpenGL and C++ uwu

**Comment by ghost** [comment]
Ok seems like electron uhh improved. Only 5mb is used now. Yay

**Comment by mdings** [comment]
See, now you don't need to write a letter after all
